
export const weatherKeyMap: Record<string, string> = {
coord: "Coordinates",
lon: "Longitude",
lat: "Latitude",
weather: "Weather Conditions",
id: "ID",
main: "Condition",
temp: "Temperature (°C)",
feels_like: "Feels Like (°C)",
temp_min: "Min Temp (°C)",
temp_max: "Max Temp (°C)",
pressure: "Pressure (hPa)",
humidity: "Humidity (%)",
sea_level: "Sea Level Pressure (hPa)",
grnd_level: "Ground Level Pressure (hPa)",
visibility: "Visibility (m)",
wind: "Wind",
speed: "Wind Speed (m/s)",
deg: "Wind Direction (°)",
clouds: "Cloudiness (%)",
all: "All Clouds (%)",
dt: "Timestamp",
sys: "System Info",
type: "Type",
country: "Country",
sunrise: "Sunrise",
sunset: "Sunset",
timezone: "Timezone Offset",
name: "City",
base: "Base",
cod: "Status Code",
};